version: '3'

services:

  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181

  nodepool_launcher:
    build: .
    depends_on:
      - zookeeper
    volumes:
      - "~/.config:/root/.config"
    environment:
      - KEYPAIR_NAME
