version: '3.6'

services:

  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181

  nodepool_launcher:
    build: .
    depends_on:
      - zookeeper
    volumes:
      - "~/.config:/root/.config"
    environment:
      - NODEPOOL_CLOUD_NAME
      - NODEPOOL_REGION_NAME
      - NODEPOOL_KEYPAIR_NAME

  web:
    image: elkozmon/zoonavigator-web:latest
    container_name: zoonavigator-web
    ports:
     - "8000:8000"
    environment:
      API_HOST: "api"
      API_PORT: 9000
    links:
     - api
    depends_on:
     - api
    restart: always

  api:
    image: elkozmon/zoonavigator-api:latest
    container_name: zoonavigator-api
    environment:
      SERVER_HTTP_PORT: 9000
    restart: always
    links:
      - zookeeper

  jenkins:
    # Modify version if you like: https://hub.docker.com/r/jenkins/jenkins/tags/
    image: jenkins/jenkins:2.107.1
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      - nodepool_launcher
      - zookeeper

volumes:
  jenkins_home:
