zookeeper-servers:
  - host: zookeeper
    port: 2181

labels:
  - name: debian
    min-ready: 6
    console-log: True

providers:
  - name: rackspace
    cloud: %NODEPOOL_CLOUD_NAME%
    driver: openstack
    region-name: %NODEPOOL_REGION_NAME%

    cloud-images:
      - name: debian-stretch-external
        image-name: nodepooljava
    pools:
      - name: main
        max-servers: 10
        labels:
          - name: debian
            cloud-image: debian-stretch-external
            flavor-name: performance1-4
            key-name: %NODEPOOL_KEYPAIR_NAME%

    boot-timeout: 600
