zookeeper-servers:
  - host: zookeeper

labels:
  - name: debian
    min-ready: 1
    console-log: True

providers:
  - name: rackspace
    cloud: %NODEPOOL_CLOUD_NAME%
    driver: openstack
    region-name: %NODEPOOL_REGION_NAME%

    cloud-images:
      - name: debian-jessie-external
        #image-name: Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
        image-name: nodepooljava
    pools:
      - name: main
        max-servers: 3
        labels:
          - name: debian
            cloud-image: debian-jessie-external
            flavor-name: performance1-4
            key-name: %NODEPOOL_KEYPAIR_NAME%

    boot-timeout: 600
